# Generated by Django 5.0.2 on 2024-02-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='slug',
        ),
        migrations.AlterField(
            model_name='logs',
            name='desc',
            field=models.CharField(max_length=500),
        ),
    ]
