# Generated by Django 5.0.2 on 2024-02-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsapp', '0002_remove_logs_slug_alter_logs_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
